export default {
  ADD_TODO_SUCCESS: 'ADD_TODO_SUCCESS',
  TOGGLE_TODO_SUCCESS: 'TOGGLE_TODO_SUCCESS',
  DELETE_TODO_SUCCESS: 'DELETE_TODO_SUCCESS',
  FETCH_TODOS_SUCCESS: 'FETCH_TODOS_SUCCESS',
  FETCH_TODOS_REQUEST: 'FETCH_TODOS_REQUEST',
  FETCH_TODOS_FAILURE: 'FETCH_TODOS_FAILURE',
  CHANGE_CURRENT_TODO: 'CHANGE_CURRENT_TODO',
  SHOW_ERROR_MSG: 'SHOW_ERROR_MSG',
  SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER'
}