export default {
  ADD_TODO_SUCCESS: 'ADD_TODO_SUCCESS',
  TOGGLE_TODO_SUCCESS: 'TOGGLE_TODO_SUCCESS',
  DELETE_TODO_SUCCESS: 'DELETE_TODO_SUCCESS',
  RECEIVE_TODOS: 'RECEIVE_TODOS',
  REQUEST_TODOS: 'REQUEST_TODOS',
  CHANGE_CURRENT_TODO: 'CHANGE_CURRENT_TODO',
  SHOW_ERROR_MSG: 'SHOW_ERROR_MSG',
  SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER'
}