export default {
  ADD_TODO: 'ADD_TODO',
  TOGGLE_TODO: 'TOGGLE_TODO',
  DELETE_TODO: 'DELETE_TODO',
  LOAD_TODOS: 'LOAD_TODOS',
  CHANGE_CURRENT_TODO: 'CHANGE_CURRENT_TODO',
  SHOW_ERROR_MSG: 'SHOW_ERROR_MSG',
  SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER'
}